language: node_js
os:
  - linux
  - osx
dist:
  - xenial
  - trusty
  - bionic
node_js:
  - stable
  - lts/*
  - "10.5"
  - "8.11"
  - "6.14"
  - "4.9"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - iojs
  - iojs-v1.0.4
install:
  - npm install
